// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace LdOrders
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
public partial class ordersOrder
{
    
    private ordersOrderActions actionsField;
    
    private List<ordersOrderCustomer> customersField;
    
    private List<ordersOrderLineItem> lineItemsField;
    
    private ordersOrderPayments paymentsField;
    
    private ordersOrderDiscounts discountsField;
    
    private ordersOrderGiftMessage giftMessageField;
    
    private List<ordersOrderShippingComments> shippingCommentsField;
    
    private static XmlSerializer serializer;
    
        [XmlElementAttribute(Order=0)]
        public virtual string sourceCode { get; set; }
        [XmlElementAttribute(Order=1)]
        public virtual System.DateTime orderDate { get; set; }
        [XmlElementAttribute(Order=2)]
        public virtual string affiliateOrderID { get; set; }
        [XmlAttributeAttribute("order-type")]
        public virtual ordersOrderOrdertype ordertype { get; set; }
        [XmlAttributeAttribute("order-id")]
        public virtual string orderid { get; set; }
    
    [XmlElementAttribute(Order=3)]
    public virtual ordersOrderActions actions
    {
        get
        {
            if ((actionsField == null))
            {
                actionsField = new ordersOrderActions();
            }
            return actionsField;
        }
        set
        {
            actionsField = value;
        }
    }
    
    [XmlArrayAttribute(Order=4)]
    [XmlArrayItemAttribute("customer", IsNullable=false)]
    public virtual List<ordersOrderCustomer> customers
    {
        get
        {
            if ((customersField == null))
            {
                customersField = new List<ordersOrderCustomer>();
            }
            return customersField;
        }
        set
        {
            customersField = value;
        }
    }
    
    [XmlArrayAttribute(Order=5)]
    [XmlArrayItemAttribute("lineItem", IsNullable=false)]
    public virtual List<ordersOrderLineItem> lineItems
    {
        get
        {
            if ((lineItemsField == null))
            {
                lineItemsField = new List<ordersOrderLineItem>();
            }
            return lineItemsField;
        }
        set
        {
            lineItemsField = value;
        }
    }
    
    [XmlElementAttribute(Order=6)]
    public virtual ordersOrderPayments payments
    {
        get
        {
            if ((paymentsField == null))
            {
                paymentsField = new ordersOrderPayments();
            }
            return paymentsField;
        }
        set
        {
            paymentsField = value;
        }
    }
    
    [XmlElementAttribute(Order=7)]
    public virtual ordersOrderDiscounts discounts
    {
        get
        {
            if ((discountsField == null))
            {
                discountsField = new ordersOrderDiscounts();
            }
            return discountsField;
        }
        set
        {
            discountsField = value;
        }
    }
    
    [XmlElementAttribute(Order=8)]
    public virtual ordersOrderGiftMessage giftMessage
    {
        get
        {
            if ((giftMessageField == null))
            {
                giftMessageField = new ordersOrderGiftMessage();
            }
            return giftMessageField;
        }
        set
        {
            giftMessageField = value;
        }
    }
    
    [XmlElementAttribute("shippingComments", Order=9)]
    public virtual List<ordersOrderShippingComments> shippingComments
    {
        get
        {
            if ((shippingCommentsField == null))
            {
                shippingCommentsField = new List<ordersOrderShippingComments>();
            }
            return shippingCommentsField;
        }
        set
        {
            shippingCommentsField = value;
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(ordersOrder));
            }
            return serializer;
        }
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current ordersOrder object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize(System.Text.Encoding encoding)
    {
        StreamReader streamReader = null;
        MemoryStream memoryStream = null;
        try
        {
            memoryStream = new MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Encoding = encoding;
            xmlWriterSettings.Indent = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new StreamReader(memoryStream, encoding);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    public virtual string Serialize()
    {
        return Serialize(System.Text.Encoding.UTF8);
    }
    
    /// <summary>
    /// Deserializes workflow markup into an ordersOrder object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output ordersOrder object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out ordersOrder obj, out Exception exception)
    {
        exception = null;
        obj = default(ordersOrder);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out ordersOrder obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public static ordersOrder Deserialize(string input)
    {
        StringReader stringReader = null;
        try
        {
            stringReader = new StringReader(input);
            return ((ordersOrder)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static ordersOrder Deserialize(Stream s)
    {
        return ((ordersOrder)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current ordersOrder object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName, encoding);
            return true;
        }
        catch (Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual bool SaveToFile(string fileName, out Exception exception)
    {
        return SaveToFile(fileName, System.Text.Encoding.UTF8, out exception);
    }
    
    public virtual void SaveToFile(string fileName)
    {
        SaveToFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
    {
        StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize(encoding);
            streamWriter = new StreamWriter(fileName, false, System.Text.Encoding.UTF8);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an ordersOrder object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output ordersOrder object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out ordersOrder obj, out Exception exception)
    {
        exception = null;
        obj = default(ordersOrder);
        try
        {
            obj = LoadFromFile(fileName, encoding);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out ordersOrder obj, out Exception exception)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8, out obj, out exception);
    }
    
    public static bool LoadFromFile(string fileName, out ordersOrder obj)
    {
        Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public static ordersOrder LoadFromFile(string fileName)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public static ordersOrder LoadFromFile(string fileName, System.Text.Encoding encoding)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
    
    #region Clone method
    /// <summary>
    /// Create a clone of this ordersOrder object
    /// </summary>
    public virtual ordersOrder Clone()
    {
        return ((ordersOrder)(MemberwiseClone()));
    }
    #endregion
}
}
#pragma warning restore
