// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace LdOrders
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true)]
public enum ordersOrderPaymentsPaymentSource
{
    
    AZ,
    
    BC,
    
    EG,
    
    MA,
    
    PA,
    
    OS,
    
    SS,
    
    BU,
    
    WM,
    
    BB,
}
}
#pragma warning restore
